In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("project.csv")
df

time  entry_id  temperature  humidity  co2ppm     type
0    2020-09-19 22:53:28 +06         1         32.0      90.0     927     Rain
1    2020-09-19 22:53:44 +06         2         32.0      90.0     928     Mist
2    2020-09-19 22:54:01 +06         3         32.0      92.0     925  Drizzle
3    2020-09-19 22:54:17 +06         4         32.0      93.0     929     Rain
4    2020-09-19 22:54:34 +06         5         32.0      93.0     930     Mist
..                       ...       ...          ...       ...     ...      ...
395  2020-09-23 13:45:54 +06       396         30.7      83.4     630  Drizzle
396  2020-09-23 13:46:14 +06       397         30.7      84.0     635     Rain
397  2020-09-23 13:46:29 +06       398         30.7      84.5     638  Drizzle
398  2020-09-23 13:46:50 +06       399         30.7      81.6     640     Rain
399  2020-09-23 13:47:05 +06       400         30.7      81.3     642  Drizzle

[400 rows x 6 columns]

In [3]:
reg = linear_model.LinearRegression()
reg.fit(df[['temperature','humidity']],df.co2ppm)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
reg.coef_

array([14.13234194, 17.52830402])

In [5]:
reg.intercept_

-1219.24355322225

In [6]:
reg.predict([[30.5, 85]])

array([701.69871756])

In [7]:
reg.predict([[32, 90]])

array([810.53875057])

In [8]:
x = df.drop(['time','entry_id','co2ppm','type'], axis='columns')
x

temperature  humidity
0           32.0      90.0
1           32.0      90.0
2           32.0      92.0
3           32.0      93.0
4           32.0      93.0
..           ...       ...
395         30.7      83.4
396         30.7      84.0
397         30.7      84.5
398         30.7      81.6
399         30.7      81.3

[400 rows x 2 columns]

In [9]:
y = df.co2ppm
y

0      927
1      928
2      925
3      929
4      930
      ... 
395    630
396    635
397    638
398    640
399    642
Name: co2ppm, Length: 400, dtype: int64

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [11]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
model.predict(x)

array([810.53875057, 810.53875057, 845.5953586 , 863.12366262,
       863.12366262, 845.5953586 , 845.5953586 , 845.5953586 ,
       845.5953586 , 887.99238443, 887.99238443, 873.86004249,
       670.31231842, 617.72740637, 705.36892646, 722.89723048,
       757.95383851, 757.95383851, 757.95383851, 757.95383851,
       740.42553449, 775.48214253, 757.95383851, 722.89723048,
       722.89723048, 722.89723048, 635.25571039, 640.51420159,
       638.76137119, 640.51420159, 637.00854079, 638.76137119,
       637.00854079, 638.76137119, 642.26703199, 640.51420159,
       637.00854079, 647.5255232 , 640.40450286, 654.53684481,
       656.28967521, 656.28967521, 666.80665762, 673.81797923,
       673.81797923, 673.81797923, 661.43846768, 673.81797923,
       673.81797923, 675.57080963, 677.32364003, 677.32364003,
       682.58213123, 691.34628324, 691.34628324, 691.34628324,
       691.34628324, 691.34628324, 689.59345284, 691.34628324,
       691.34628324, 693.09911364, 693.09911364, 693.09

In [15]:
model.score(x,y)

0.9321867223303033